### ISSUE TITLE
Custom alphabet crashes the app

### ISSUE THREAD

**Issue by arbinish** [sommer/loxodo#21]
If you set a custom alphabet set in your loxodo.ini, the app crashes during launch.
Looks like a bug in config.py

``` python
 55         if self._parser.has_option("base", "alphabet"):
 56             self.alphabet = int(self._parser.get("base", "alphabet"))
```

Not sure why we are casting to int, we need to drop the cast there.

**Comment by shamilbi** [comment]
this has been [fixed](https://github.com/sommer/loxodo/blob/7add982135545817e9b3e2bbd0d27a2763866133/src/config.py#L68)

**Comment by sommer** [comment]
Right you are. Thanks!
